### ISSUE TITLE
possible bad merge of bdpt.h and bdpt.cpp

### ISSUE THREAD

**Issue by felipegb94** [cmu-ci-lab/MitsubaToFRenderer#1]
Hi,

I recently pulled the latest changes into my fork of MitsubaToFRenderer and when I tried to compile the code I ran into the following error:

```
include/../src/integrators/bdpt/bdpt.h:76:15: error: redeclaration of ‘unsigned int mitsuba::BDPTConfiguration::m_tBounces’
  unsigned int m_tBounces;
```

I looked at the `bdpt.h` file and it looks like from lines 66 through 77 you have some duplicate code. I also noticed this in `bdpt.cpp` in lines 225 to 238.

Deleting the duplicate code fixed the issue for me.

Thanks!
Felipe

**Comment by AdithyaPediredla** [comment]
Thank you, Felipe. A previous merge created duplicate code that I haven't noticed. Fixed it now.
